// test/unit/contracts-pending.ts
// Endpoints still waiting for a contract in domain/contracts/registry.ts,
// one line per method, named as the registry names routes.
//
// This list only shrinks. When you give an endpoint its contract and its
// contract test (test/integration/contracts/), take its line out and lower
// PENDING_COUNT to match. A new endpoint never goes on this list: it ships
// with its contract, and test/unit/contract-coverage.test.ts fails until it
// does. Raising PENDING_COUNT is the one way around that, and a reviewer
// should refuse it.
//
// The lines marked as serving an image, CSV text or Stripe's event body do
// not answer with JSON; whether they get a contract for their error answers
// only, or move to the coverage test's excluded list with that reason, is
// decided when each is next changed.

export const PENDING_COUNT = 118

export const PENDING_CONTRACTS: readonly string[] = [
  'GET admin/announcement',
  'POST admin/announcement',
  'PATCH admin/announcement/[id]',
  'DELETE admin/announcement/[id]',
  'GET admin/audit',
  'GET admin/board-seats',
  'POST admin/board-seats',
  'GET admin/campaigns',
  'POST admin/campaigns',
  'GET admin/campaigns/[id]',
  'POST admin/campaigns/preview',
  'POST admin/campaigns/test',
  'POST admin/champions',
  'PATCH admin/champions/[id]',
  'DELETE admin/champions/[id]',
  'POST admin/clubs',
  'GET admin/clubs/[id]',
  'PATCH admin/clubs/[id]',
  'DELETE admin/clubs/[id]',
  'POST admin/clubs/[id]/logo',
  'GET admin/clubs/[id]/news',
  'POST admin/clubs/[id]/news',
  'DELETE admin/clubs/[id]/news/[newsId]',
  'GET admin/clubs/[id]/officers',
  'POST admin/clubs/[id]/officers',
  'DELETE admin/clubs/[id]/officers/[officerId]',
  'GET admin/clubs/[id]/roster',
  'POST admin/impersonate/[memberId]',
  'POST admin/impersonate/end',
  'GET admin/members',
  'DELETE admin/members/[id]',
  'PATCH admin/members/[id]/club',
  'PATCH admin/members/[id]/membership',
  'PATCH admin/members/[id]/name',
  'PATCH admin/members/[id]/role',
  'GET admin/members/export', // serves CSV text
  'POST admin/officer-photo',
  'DELETE admin/officer-photo',
  'GET admin/posts',
  'POST admin/posts',
  'GET admin/posts/[id]',
  'PATCH admin/posts/[id]',
  'DELETE admin/posts/[id]',
  'POST admin/posts/[id]/image',
  'DELETE admin/posts/[id]/image',
  'PUT admin/seat-regions',
  'GET admin/support',
  'GET admin/support/[id]',
  'POST admin/support/[id]',
  'PATCH admin/support/[id]',
  'DELETE admin/support/[id]',
  'DELETE admin/tournaments/[id]',
  'POST admin/tournaments/[id]/announce',
  'GET admin/tournaments/[id]/directors',
  'POST admin/tournaments/[id]/directors',
  'DELETE admin/tournaments/[id]/directors',
  'POST admin/tournaments/[id]/games',
  'PATCH admin/tournaments/[id]/games/[gameId]',
  'POST admin/tournaments/[id]/generate-pairings',
  'GET admin/tournaments/[id]/manage',
  'GET admin/tournaments/[id]/rating-report',
  'PATCH admin/tournaments/[id]/registration',
  'DELETE admin/tournaments/[id]/rounds/[round]',
  'POST admin/tournaments/[id]/waitlist',
  'POST admin/tournaments/[id]/walk-ins',
  'GET announcement',
  'GET board/my-seats',
  'GET board/seats',
  'GET board/tickets',
  'GET board/tickets/[id]',
  'POST board/tickets/[id]',
  'PATCH board/tickets/[id]',
  'DELETE board/tickets/[id]',
  'GET champions',
  'GET clearinghouse',
  'GET clubs',
  'GET clubs/[id]',
  'GET clubs/[id]/logo', // serves an image
  'GET contact',
  'POST contact',
  'POST donations/checkout',
  'GET facebook-posts',
  'GET governance/board',
  'POST governance/board',
  'PUT governance/board/[id]',
  'DELETE governance/board/[id]',
  'GET governance/documents',
  'POST governance/documents',
  'PUT governance/documents/[id]',
  'DELETE governance/documents/[id]',
  'GET health',
  'GET me',
  'POST me',
  'PATCH me',
  'GET me/children',
  'POST me/children',
  'PATCH me/children/[id]',
  'DELETE me/children/[id]',
  'POST membership/checkout',
  'POST membership/confirm',
  'GET news',
  'GET officer-photos/[key]', // serves an image
  'GET post-images/[id]', // serves an image
  'GET posts',
  'GET posts/[slug]',
  'POST registrations/[id]/pay',
  'POST scan',
  'POST stripe/webhook', // Stripe's event body, signature checked on the raw text
  'GET support',
  'POST support',
  'GET support/[id]',
  'POST support/[id]',
  'GET tournaments/[id]',
  'GET tournaments/[id]/remind',
  'POST tournaments/[id]/remind',
  'DELETE tournaments/[id]/remind',
  'GET uscf/lookup',
  'GET uscf/search',
]
