name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 9 * * 1,4'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: curl ${{ secrets.SUPABASE_URL }}/rest/v1/
